### ISSUE TITLE
model checkpoint

### ISSUE THREAD

**Issue by mahmoudEltaher** [romaintha/pytorch_pointnet#3]
Hi, I was trying with new data.Can you please help me what should i give as model checkpoint.

**Comment by romaintha** [comment]
Hi @mahmoudEltaher 
If you are speaking about training on new data, you eventually do not need a checkpoint.
If you are speaking about inference on new data, the checkpoint shall be the checkpoint produced by your training above.

**Comment by mahmoudEltaher** [comment]
I try to train the model on ShapeNet data set 
but when i run the command i got the following error 
python train.py shapenet ../03001627/ classification ../output/ --number_of_points 2500 --batch_size 32 --epochs 50 --learning_rate 0.001 --number_of_workers 4
Traceback (most recent call last):
  File "train.py", line 188, in <module>
    args.model_checkpoint)
  File "train.py", line 40, in train
    number_of_points=number_of_points)
  File "D:\Cottbus\code\pytorch_pointnet-master\datasets.py", line 55, in __init__
    with open(category_file, 'r') as fid:
FileNotFoundError: [Errno 2] No such file or directory: '../03001627/synsetoffset2category.txt'

Waiting for your kindly response.

**Comment by romaintha** [comment]
Well, I think the error is rather informative. You don't have the required dataset files. You should download correctly the dataset. I will close the issue.

**Comment by mahmoudEltaher** [comment]
Thanks for your response 
I redownload the data  :

but i got the following error.

python train.py shapenet ../../shapenetcore_partanno_segmentation_benchmark_v0/ classification ../output/ --number_of_points 2500 --batch_size 32 --epochs 50 --learning_rate 0.001 --number_of_workers 4
Traceback (most recent call last):----------------------------------------| 0.00% [0/380 00:00<00:00]
  File "train.py", line 188, in <module>
    args.model_checkpoint)
  File "train.py", line 95, in train
    preds, feature_transform = model(points)
  File "C:\Users\Mahmoud Eltaher\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Cottbus\code\pytorch_pointnet-master\model\pointnet.py", line 113, in forward
    x, feature_transform = self.base_pointnet(x)
  File "C:\Users\Mahmoud Eltaher\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Cottbus\code\pytorch_pointnet-master\model\pointnet.py", line 70, in forward
    input_transform = self.input_transform(x)
  File "C:\Users\Mahmoud Eltaher\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Cottbus\code\pytorch_pointnet-master\model\pointnet.py", line 29, in forward
    x = F.relu(self.bn_1(self.conv_1(x)))
  File "C:\Users\Mahmoud Eltaher\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\Mahmoud Eltaher\Anaconda3\lib\site-packages\torch\nn\modules\conv.py", line 176, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CuDNN error: CUDNN_STATUS_SUCCESS

Waiting for your kindly response.
